language: node_js
node_js:
  - "6"
install:
  - yarn install
script:
  - cp ./config/config.example.yml ./config/config.yml
  - cp ./config/keycloak.example.json ./config/keycloak.json
  - npm run grunt-t1t
  - NODE_ENV=test ./node_modules/.bin/_mocha 'server/**/*.spec.js'
  - npm run deploy-t1t