language: node_js
node_js:
  - "6"
before_install:
  - echo "registry=https://repo.t1t.be/repository/npm-group\n_auth=\${NPM_TOKEN}\nemail=development@trust1team.com\nalways-auth=true" > .npmrc
install:
  - yarn install
script:
  - cp ./config/config.example.yml ./config/config.yml
  - cp ./config/keycloak.example.json ./config/keycloak.json
  - npm run grunt
  - NODE_ENV=test ./node_modules/.bin/_mocha 'server/**/*.spec.js'
  - npm run deploy
